Mongoose addition
platform-for-testing/back pull request #20
Opened 2017-11-08 10:01 UTC by vnormatov

- Переписал  все endpoints на работу через mongoose
- Тесты все отключил, их нужно писать заново
- Есть предложение, каждый пишет тесты на свой endpoint)

2017-11-08 19:37 UTC, AlexDoh reviewed
Круто! Но зачем убирать development.json ? Без него сейчас не стартует

2017-11-08 20:02 UTC, vnormatov commented
он на самом деле есть, только зашифрованный)

On Wed, Nov 8, 2017 at 9:37 PM, AlexDoh <notifications@github.com> wrote:

> *@AlexDoh* commented on this pull request.
>
> Круто! Но зачем убирать development.json ? Без него сейчас не стартует
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/platform-for-testing/back/pull/20#pullrequestreview-75223298>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARTo835JW_Si1_1qsKRuVJSvkuKfEENRks5s0gMKgaJpZM4QWH25>
> .
>

2017-11-08 22:30 UTC, pavlom0x requested changes

2017-11-08 22:30 UTC, PavelMelnyk commented on lib/db/index.js
> +    async create(collection, data) {
```
try {
    cont res = await this.client.collection(collection).insert(data);
    return res.ops[0];
} catch (error) {
    this.logger.error(error, 'DB creation error');
    return false;
}
```

2017-11-08 22:30 UTC, PavelMelnyk commented on lib/models/activationShema.js
> +        validate: validators.isDate('YYYY-MM-DD')
we also need to tack hours minutes and seconds

2017-11-08 22:30 UTC, PavelMelnyk commented on lib/models/activationShema.js
> +    dateStart: {
can we use standard date type?

2017-11-08 22:30 UTC, PavelMelnyk commented on lib/models/activationShema.js
> +    participants: {
as I understand, at the beginning participants = 0

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/models/activationOptionsSchema.js
> +module.exports = mongoose.model('activationOptionsModel', activationOptionsSchema, 'activationOptions');
можна і так залишити, але всюди я бачив, що модель називають як конструктор, її ж потім як конструктор і використовується. Наприклад ```Activation```

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/models/activationOptionsSchema.js
> +module.exports = mongoose.model('activationOptionsModel', activationOptionsSchema, 'activationOptions');
А для чого третій аргумент?

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/models/questionSchema.js
> +	_id: {
думаю, якщо uuid, то вже не потрібно ```_id```, краще просто ```id``` тим більше ObjectId ж нікуди по ідеї не пропав

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/routes/activation.js
> +			.exec((err, respondent) => {
mongoose ж ніби вміє з промісами працювати, а якщо так, то ```await``` не потрібен

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/routes/activation.js
> +		await activationShema
якщо так працює, то ок, але я всюди бачив ```const Activation = require('mongoose').model('Activation')```
і потім ```Activation.find```, ```new Activation({})``` і т п

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/routes/index.js
> +	const users = new Users(db, logger);
конструктор мав би бути в однині ```Users -> User```

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/routes/user.js
> +	async getUsers(ctx, offset = 0, limit = 10) {
такі штуки можна додавати в Model.methods чи Model.stati і не створювати окремий клас

2017-11-14 10:39 UTC, YuriiHoliuk commented on lib/routes/user.js
> +	async getUsers(ctx, offset = 0, limit = 10) {
але юзера я зроблю при логіні

2017-11-14 10:39 UTC, YuriiHoliuk commented on package.json
> +    "uuid": "^3.1.0",
цей uuid напевне не потрібний

2017-11-15 07:57 UTC, vnormatov commented on lib/models/activationOptionsSchema.js
> +module.exports = mongoose.model('activationOptionsModel', activationOptionsSchema, 'activationOptions');
Это коллекция из базы

2017-11-15 08:28 UTC, vnormatov commented on lib/routes/quiz.js
> +		const validated = joi.validate(quiz, quizValidation);
Тут точно нужна валидация? Я думал, что на этапе создания обьекта вопроса происходит валидация средствами mongoose.

2017-11-15 08:46 UTC, YuriiHoliuk commented on lib/routes/quiz.js
> +		const validated = joi.validate(quiz, quizValidation);
Думаю, що не потрібно

2017-11-16 15:41 UTC, vnormatov commented on package.json
> +    "uuid": "^3.1.0",
нужен, мы генерируем id обьекта в базе с помощью него

2017-11-16 15:41 UTC, vnormatov commented on lib/routes/quiz.js
> +		const validated = joi.validate(quiz, quizValidation);
Видать нужна)

2017-11-18 10:45 UTC, AlexDoh approved these changes

2017-11-18 10:46 UTC, YuriiHoliuk approved these changes

2017-11-18 10:47 UTC, pavlom0x approved these changes

2017-11-18 10:48 UTC, merged