Fixed cleaning data after tests.
platform-for-testing/back pull request #27
Opened 2017-11-20 22:18 UTC by AlexDoh

Added cleaning collections after each test execution.

2017-11-21 05:53 UTC, YuriiHoliuk commented on test/quiz/quiz.spec.js
> +			await pftServer.db.removeCollection('quizes');
Це точно спрацює після виконання колбека, а не після? І взагалі треба випилити ці колбека.
І замість того, щоб в кожному кейсів додавати, можна використати afterEach, або просто after, як в інших тестах

2017-11-21 08:08 UTC, tatsiak requested changes

2017-11-21 08:08 UTC, tatsiak commented on test/quiz/quiz.spec.js
> +			await pftServer.db.removeCollection('quizes');
Согласен с Юрой лучше использовать after или afterEach.
Выше видно что удаление есть в after - скорее всего оно здесь просто не нужно.

2017-11-21 08:39 UTC, PavelMelnyk commented on test/quiz/quiz.spec.js
> +			await pftServer.db.removeCollection('quizes');
зачем опять колбеки?)
можно ж на евейтах написать

```
const response = await request
	.post('/admin/tests')
	.set('Accept', 'application/json')
	.set('Authorization', `Bearer ${token}`)
	.send(quizTwo)
	.expect(200);

const quiz = Object.assign({}, response.body);
delete quiz._id;
delete quiz.id;
delete quiz.__v;
quiz.questions.forEach(q => uuidv4.valid(q));
delete quiz.questions;
delete quizTwo.questions;
assert.deepEqual(quiz, quizTwo);
```

2017-11-23 12:20 UTC, tatsiak approved these changes

2017-11-23 12:22 UTC, merged